# Generated by Django 4.1.3 on 2024-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_eventbook_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventBook',
        ),
    ]
