# Generated by Django 4.1.3 on 2024-12-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_delete_eventbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.RemoveField(
            model_name='tablebook',
            name='occasion',
        ),
        migrations.AlterField(
            model_name='tablebook',
            name='person',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='tablebook',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.table'),
        ),
    ]
