# Generated by Django 4.1.3 on 2024-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
